server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: desktop-cat-server
  profiles:
    default: local

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{requestId:-system}] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
