server:
  address: 127.0.0.1
  port: 8080

spring:
  application:
    name: desktop-cat-server
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
