spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      schema: public
  flyway:
    default-schema: public
    schemas: public
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6380}
      connect-timeout: 2s
      timeout: 2s
  session:
    store-type: redis
    timeout: 12h
    redis:
      namespace: desktop-cat:session

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
