CREATE TABLE knowledge_chat (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(80) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_knowledge_chat_user
        FOREIGN KEY (user_id) REFERENCES app_user (user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_knowledge_chat_title
        CHECK (char_length(btrim(title)) BETWEEN 1 AND 80),
    CONSTRAINT ck_knowledge_chat_version
        CHECK (version >= 0)
);

CREATE INDEX idx_knowledge_chat_user_updated
    ON knowledge_chat (user_id, updated_at DESC, chat_id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE knowledge_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    sources JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_knowledge_message_chat
        FOREIGN KEY (chat_id) REFERENCES knowledge_chat (chat_id) ON DELETE RESTRICT,
    CONSTRAINT ck_knowledge_message_role
        CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_knowledge_message_content
        CHECK (char_length(btrim(content)) > 0),
    CONSTRAINT ck_knowledge_message_user_content_length
        CHECK (role <> 'USER' OR char_length(content) <= 500),
    CONSTRAINT ck_knowledge_message_sources
        CHECK (sources IS NULL OR jsonb_typeof(sources) = 'array')
);

CREATE INDEX idx_knowledge_message_chat
    ON knowledge_message (chat_id, message_id DESC);

COMMENT ON TABLE knowledge_chat IS '知识库问答对话';
COMMENT ON COLUMN knowledge_chat.chat_id IS '知识库对话主键';
COMMENT ON COLUMN knowledge_chat.user_id IS '对话所属用户，同时作为租户键';
COMMENT ON COLUMN knowledge_chat.title IS '对话标题，默认根据首个问题生成';
COMMENT ON COLUMN knowledge_chat.version IS '对话内容版本，用于并发控制和 Redis 缓存一致性校验';
COMMENT ON COLUMN knowledge_chat.created_at IS '对话创建时间';
COMMENT ON COLUMN knowledge_chat.updated_at IS '最后一轮问答完成时间';
COMMENT ON COLUMN knowledge_chat.deleted_at IS '逻辑删除时间，为空表示未删除';

COMMENT ON TABLE knowledge_message IS '知识库对话中的用户问题和助手回答';
COMMENT ON COLUMN knowledge_message.message_id IS '消息主键，同时用于确定同一对话内的消息顺序';
COMMENT ON COLUMN knowledge_message.chat_id IS '消息所属知识库对话';
COMMENT ON COLUMN knowledge_message.role IS '消息角色：USER 用户或 ASSISTANT 助手';
COMMENT ON COLUMN knowledge_message.content IS '用户问题或助手回答正文';
COMMENT ON COLUMN knowledge_message.sources IS '助手回答使用的知识库来源快照，用户消息为空';
COMMENT ON COLUMN knowledge_message.created_at IS '消息创建时间';
