CREATE TABLE cat_profile (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_key VARCHAR(64) NOT NULL,
    cat_name VARCHAR(20) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cat_profile_profile_key UNIQUE (profile_key),
    CONSTRAINT ck_cat_profile_cat_name_not_blank CHECK (char_length(trim(cat_name)) > 0),
    CONSTRAINT ck_cat_profile_version_nonnegative CHECK (version >= 0)
);

INSERT INTO cat_profile (profile_key, cat_name)
VALUES ('primary', '小饼干');
