CREATE TABLE personal_record (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type VARCHAR(20) NOT NULL,
    title VARCHAR(120),
    content TEXT NOT NULL,
    record_date DATE NOT NULL,
    mood VARCHAR(32),
    recall_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    rag_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_personal_record_type
        CHECK (record_type IN ('DIARY', 'THOUGHT', 'WORK_NOTE')),
    CONSTRAINT ck_personal_record_title_not_blank
        CHECK (title IS NULL OR char_length(trim(title)) > 0),
    CONSTRAINT ck_personal_record_content_not_blank
        CHECK (char_length(trim(content)) > 0),
    CONSTRAINT ck_personal_record_mood_not_blank
        CHECK (mood IS NULL OR char_length(trim(mood)) > 0),
    CONSTRAINT ck_personal_record_version_nonnegative
        CHECK (version >= 0)
);

CREATE INDEX idx_personal_record_active_date
    ON personal_record (record_date DESC, record_id DESC)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE personal_record IS '个人文章记录，包括日记、心得和实习笔记';
COMMENT ON COLUMN personal_record.record_id IS '文章记录主键';
COMMENT ON COLUMN personal_record.record_type IS '文章类型：DIARY、THOUGHT、WORK_NOTE';
COMMENT ON COLUMN personal_record.title IS '文章标题，可为空';
COMMENT ON COLUMN personal_record.content IS '用户保存的原始正文';
COMMENT ON COLUMN personal_record.record_date IS '文章内容对应的日期';
COMMENT ON COLUMN personal_record.mood IS '记录文章时的心情，可为空';
COMMENT ON COLUMN personal_record.recall_enabled IS '是否加入文章温馨回忆轮播';
COMMENT ON COLUMN personal_record.rag_enabled IS '是否允许进入 RAG 检索范围';
COMMENT ON COLUMN personal_record.version IS '乐观锁版本';
COMMENT ON COLUMN personal_record.created_at IS '创建时间';
COMMENT ON COLUMN personal_record.updated_at IS '最后更新时间';
COMMENT ON COLUMN personal_record.deleted_at IS '逻辑删除时间，为空表示未删除';
