CREATE TABLE daily_emotion (
    emotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    record_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_daily_emotion_content
        CHECK (char_length(trim(content)) > 0)
);

CREATE INDEX idx_daily_emotion_date
    ON daily_emotion (record_date DESC, created_at ASC);

COMMENT ON TABLE daily_emotion IS '用户通过桌面小猫记录的每日情绪碎片';
COMMENT ON COLUMN daily_emotion.emotion_id IS '情绪记录主键';
COMMENT ON COLUMN daily_emotion.content IS '用户输入的原始文字';
COMMENT ON COLUMN daily_emotion.record_date IS '情绪所属的本地日期';
COMMENT ON COLUMN daily_emotion.created_at IS '情绪记录时间';
