CREATE TABLE reminder (
    reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(200) NOT NULL,
    remind_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    completed_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT ck_reminder_content
        CHECK (char_length(trim(content)) > 0),
    CONSTRAINT ck_reminder_status
        CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT ck_reminder_completion
        CHECK ((status = 'PENDING' AND completed_at IS NULL)
            OR (status = 'COMPLETED' AND completed_at IS NOT NULL)),
    CONSTRAINT ck_reminder_version
        CHECK (version >= 0)
);

CREATE INDEX idx_reminder_active_status_time
    ON reminder (status, remind_at, reminder_id)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE reminder IS '用户的待办与一次性提醒';
COMMENT ON COLUMN reminder.reminder_id IS '提醒主键';
COMMENT ON COLUMN reminder.content IS '提醒内容';
COMMENT ON COLUMN reminder.remind_at IS '提醒触发时间';
COMMENT ON COLUMN reminder.status IS '提醒状态：PENDING 或 COMPLETED';
COMMENT ON COLUMN reminder.completed_at IS '提醒完成时间';
COMMENT ON COLUMN reminder.version IS '乐观锁版本';
COMMENT ON COLUMN reminder.created_at IS '创建时间';
COMMENT ON COLUMN reminder.updated_at IS '最后更新时间';
COMMENT ON COLUMN reminder.deleted_at IS '逻辑删除时间';
