CREATE TABLE app_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_app_user_username
        UNIQUE (username),
    CONSTRAINT ck_app_user_username_not_blank
        CHECK (char_length(btrim(username)) > 0),
    CONSTRAINT ck_app_user_username_trimmed
        CHECK (username = btrim(username)),
    CONSTRAINT ck_app_user_username_length
        CHECK (char_length(username) BETWEEN 3 AND 32),
    CONSTRAINT ck_app_user_password_hash_not_blank
        CHECK (char_length(btrim(password_hash)) > 0),
    CONSTRAINT ck_app_user_status
        CHECK (status IN ('ACTIVE', 'DISABLED'))
);

COMMENT ON TABLE app_user IS '系统用户表';
COMMENT ON COLUMN app_user.user_id IS '用户主键，由数据库自动生成';
COMMENT ON COLUMN app_user.username IS '登录用户名，系统内唯一';
COMMENT ON COLUMN app_user.password_hash IS '密码哈希，不保存明文密码';
COMMENT ON COLUMN app_user.status IS '用户状态：ACTIVE 正常，DISABLED 禁用';
COMMENT ON COLUMN app_user.created_at IS '用户创建时间';
COMMENT ON COLUMN app_user.updated_at IS '用户信息最后更新时间';
