CREATE TABLE photo (
    photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_photo_user
        FOREIGN KEY (user_id) REFERENCES app_user (user_id),
    CONSTRAINT uk_photo_storage_key
        UNIQUE (storage_key),
    CONSTRAINT ck_photo_storage_key_not_blank
        CHECK (char_length(btrim(storage_key)) > 0)
);

CREATE INDEX idx_photo_user_active_created
    ON photo (user_id, created_at DESC, photo_id DESC)
    WHERE deleted_at IS NULL;

COMMENT ON TABLE photo IS '用户上传并自动加入首页轮播的照片';
COMMENT ON COLUMN photo.photo_id IS '照片主键';
COMMENT ON COLUMN photo.user_id IS '照片所属用户';
COMMENT ON COLUMN photo.storage_key IS '裁剪后 WebP 文件在存储根目录下的相对路径';
COMMENT ON COLUMN photo.created_at IS '照片上传时间';
COMMENT ON COLUMN photo.deleted_at IS '逻辑删除时间，为空表示参与轮播';
