CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS ai;

CREATE TABLE ai.document_chunk (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    source_version INTEGER NOT NULL,
    owner_user_id BIGINT NOT NULL,
    chunk_index INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    embedding vector(1536) NOT NULL,
    embedding_model VARCHAR(120) NOT NULL,
    embedding_dimension INTEGER NOT NULL DEFAULT 1536,
    index_status VARCHAR(20) NOT NULL DEFAULT 'READY',
    index_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ai_document_chunk_source_type
        CHECK (source_type IN ('PERSONAL_RECORD', 'DAILY_EMOTION', 'PHOTO_OCR', 'IMPORT')),
    CONSTRAINT ck_ai_document_chunk_source_version
        CHECK (source_version > 0),
    CONSTRAINT ck_ai_document_chunk_index
        CHECK (chunk_index >= 0),
    CONSTRAINT ck_ai_document_chunk_content
        CHECK (length(trim(content)) > 0),
    CONSTRAINT ck_ai_document_chunk_embedding_dimension
        CHECK (embedding_dimension = 1536),
    CONSTRAINT ck_ai_document_chunk_status
        CHECK (index_status IN ('PENDING', 'READY', 'FAILED', 'DELETED')),
    CONSTRAINT uk_ai_document_chunk_version
        UNIQUE (source_type, source_id, source_version, chunk_index, embedding_model)
);

CREATE INDEX ai_document_chunk_owner_idx
    ON ai.document_chunk (owner_user_id);

CREATE INDEX ai_document_chunk_source_idx
    ON ai.document_chunk (source_type, source_id, source_version);

CREATE INDEX ai_document_chunk_ready_owner_idx
    ON ai.document_chunk (owner_user_id, source_type)
    WHERE index_status = 'READY';

CREATE INDEX ai_document_chunk_embedding_hnsw_idx
    ON ai.document_chunk
    USING hnsw (embedding vector_cosine_ops);
